# -*- coding: utf-8 -*-
"""medical_re.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nddzA4hsk1pr9u1HobaxbAJr2M1QAr-K
"""

import random
import json
import numpy as np
import torch
import torch.nn as nn
# from constant import ProductionConfig as Path
from transformers import BertTokenizer, BertModel
from torch.optim import AdamW

import gc
import random
import time
import re

class config:
    batch_size = 32 # 每批训练 32 条样本
    max_seq_len = 256 #BERT 输入序列最大 256 个 token，超过截断，不足填充
    num_p = 23 #关系谓词种类数，需和 predicate.json 的键数量一致
    learning_rate = 1e-5 #AdamW 优化器学习率（BERT 微调常用值）
    EPOCH = 2 #训练轮数，整个数据集遍历 2 遍

    PATH_SCHEMA = "D:/CMe_KG/CMeKG/model/medical_re/predicate.json"
    PATH_TRAIN = 'D:/CMe_KG/CMeKG/model/medical_re/train_example.json'
    PATH_BERT = "D:/CMe_KG/CMeKG/model/medical_re/"
    PATH_MODEL = "D:/CMe_KG/CMeKG/model/medical_re/model_re.pkl"
    PATH_SAVE = 'D:/CMe_KG/CMeKG/save/model_re_trained.pkl'
    tokenizer = BertTokenizer.from_pretrained("D:/CMe_KG/CMeKG/model/medical_re/vocab.txt")

    id2predicate = {}
    predicate2id = {}



class IterableDataset(torch.utils.data.IterableDataset):
    def __init__(self, data, random):
        super(IterableDataset).__init__()
        self.data = data
        self.random = random
        self.tokenizer = config.tokenizer #/model/medical_re/vocab.txt

    def __len__(self):
        return len(self.data)

  #示例
  # 暴力子串搜索，在 token ID 序列中定位主体/客体的位置。
  #
  # sequence: [101, 1963, 2142, 1068, 2538, 1064, 3215, 102, 0, 0, 0, ...]
  #           [CLS] 阿  莫  西  林  不  可  食  用 ... [PAD][PAD]
  #
  # pattern:  [1963, 2142, 1068, 2538]   ← "阿莫西林" 去掉 [CLS][SEP] 后的 token ID
  #
  # 逐位滑动比较:
  #   i=1: [1963, 2142, 1068, 2538] == pattern? ✓ → 返回 1
  #
  # 本质就是用 滑动窗口 遍历 sequence，找 pattern 完全匹配的起始索引。找到则返回起始位置，找不到返回 -1。
  #
  # 复杂度 O(n×m)，但这里 sequence 最长 256、pattern 一般 2-6 个 token，所以足够快，不需要 KMP 等高级算法。

    def search(self, sequence, pattern):
        n = len(pattern)
        for i in range(len(sequence)):
            if sequence[i:i + n] == pattern:
                return i
        return -1

    def process_data(self):
        idxs = list(range(len(self.data)))
        if self.random:
            np.random.shuffle(idxs) #打乱顺序
        batch_size = config.batch_size
        max_seq_len = config.max_seq_len
        num_p = config.num_p

          # ┌──────────────────────┬─────────────────┬────────────────────────────────────────┐
          # │         字段         │     初始化      │                后续赋值                │
          # ├──────────────────────┼─────────────────┼────────────────────────────────────────┤
          # │ batch_token_ids      │ np.zeros (92行) │ self.tokenizer.encode(...) 填入 (92行) │
          # ├──────────────────────┼─────────────────┼────────────────────────────────────────┤
          # │ batch_mask_ids       │ np.zeros (84行) │ = 1 标记真实 token (102行)             │
          # ├──────────────────────┼─────────────────┼────────────────────────────────────────┤
          # │ batch_segment_ids    │ np.zeros (85行) │ 没有任何后续赋值                       │
          # ├──────────────────────┼─────────────────┼────────────────────────────────────────┤
          # │ batch_subject_labels │ np.zeros (87行) │ = 1 标记主体位置 (137-138行)           │
          # ├──────────────────────┼─────────────────┼────────────────────────────────────────┤
          # │ batch_object_labels  │ np.zeros (88行) │ = 1 标记客体位置 (151-152行)           │
          # └──────────────────────┴─────────────────┴────────────────────────────────────────┘

        batch_token_ids = np.zeros((batch_size, max_seq_len), dtype=np.int64)
        batch_mask_ids = np.zeros((batch_size, max_seq_len), dtype=np.int64)
        # 这行创建了一个 (32, 256) 的全零数组。而且它是整个 process_data() 中唯一涉及 batch_segment_ids 的代码——初始化完之后再也没有任何地方修改过它的值，所以它始终保持全 0。
        batch_segment_ids = np.zeros((batch_size, max_seq_len), dtype=np.int64)
        batch_subject_ids = np.zeros((batch_size, 2), dtype=np.int64)
        batch_subject_labels = np.zeros((batch_size, max_seq_len, 2), dtype=np.int64)
        batch_object_labels = np.zeros((batch_size, max_seq_len, num_p, 2), dtype=np.int64)
        batch_i = 0
        for i in idxs:
            text = self.data[i]['text'] #'(3)用前必须详细18种氨基酸注射液的检查药液，如发现瓶身有破裂、漏气、变色、发霉、沉淀、变质等异常现象时绝对不应使用'
            batch_token_ids[batch_i, :] = self.tokenizer.encode(text, max_length=max_seq_len, padding='max_length',
                                                                truncation=True, add_special_tokens=True) #将文本转成 BERT token ID 序列，填充/截断到 256 长度
            # BERT的两个特殊占位token：
            # [CLS]（Classification）— 放在序列最开头，对应ID101。BERT用它聚合整句信息做分类任务，在这个代码里没被直接使用，但BERT模型需要它。
            # [SEP]（Separator）— 放在序列末尾，对应ID102。用于分隔句子（双句任务），单句时作为结束标记。
            # 如：原始文本:"高血压病人不可食用阿莫西林"
            #       编码后 token 序列: [CLS] 高 血 压 病 人 不 可 食 用 阿 莫 西 林 [SEP]
            #                          ↑                                       ↑
            #                         101                                     102

            batch_mask_ids[batch_i, :len(text) + 2] = 1 #前 len(text)+2 个位置（含 [CLS] 和 [SEP]）设为 1，其余 pad（剩下的位置，如句子长度为8，那填满8个位置后多余的空位用0填充） 位置保持 0
            spo_list = self.data[i]['spo_list'] #取出该句所有 SPO 三元组 [[s,p,o], ...]
            idx = np.random.randint(0, len(spo_list), size=1)[0] #相当于每次都是随机选一个三元组，取出它的主体（S）作为当前样本的"训练主体"

            # Python 切片中 -1 表示倒数第一个元素，所以 [1:-1] 的含义：
            #
            #   原始编码结果: [101, 1963, 2142, 1068, 102]
            #                 [CLS]  阿   莫   西   [SEP]
            #                   ↑                    ↑
            #                  索引0               索引-1
            #
            #   [1:-1] 切片后: [1963, 2142, 1068]
            #                   阿   莫   西

            s_rand = self.tokenizer.encode(spo_list[idx][0])[1:-1] # 把选中的主体（S）文字转成 token ID，去掉首尾的 [CLS]/[SEP]
            s_rand_idx = self.search(list(batch_token_ids[batch_i, :]), s_rand) #在已编码的整句 token 序列中，暴力搜索主体（S）所在text的开始索引位置
            batch_subject_ids[batch_i, :] = [s_rand_idx, s_rand_idx + len(s_rand) - 1] #S所在text的起始和终止索引位置，供 Model4po 定位
            # print('spo_list为：',len(spo_list))
            for j in range(len(spo_list)):
                spo = spo_list[j]
                s = self.tokenizer.encode(spo[0])[1:-1] #主体文字 → token ID（去头尾 [CLS][SEP]）
                p = config.prediction2id[spo[1]] #关系名 → 数字 ID（如 "不良反应" → 8）,predicate.json对应，从0开始
                o = self.tokenizer.encode(spo[2])[1:-1] #客体文字 → token ID（同样去头尾）
                s_idx = self.search(list(batch_token_ids[batch_i]), s) #在整句 token 中定位主体起始索引
                o_idx = self.search(list(batch_token_ids[batch_i]), o) #在整句 token 中定位客体起始索引
                if s_idx != -1 and o_idx != -1: #主体（S）和客体（O）都存在的话进入

                  # batch_subject_labels— 标记所有主体
                  # 无条件执行 — 只要当前 SPO 的主体和客体在序列中能找到，就标记主体位置。这样 Model4s 要学的是找出句中所有主体。
                  #
                  # token:   [CLS] 阿 莫 西  林  治  疗  高  血  压  [SEP] [PAD]...
                  # 主体起始:       1  0  0  0  0  0  0  1  0  0   0     0
                  # 主体结束:       0  0  0  1  0  0  0  0  1  0   0     0
                  #                ↑_____阿莫西林____↑       ↑_高血压_↑

                    batch_subject_labels[batch_i, s_idx, 0] = 1 #预测第 s_idx 个Token是不是S的起始位置
                    batch_subject_labels[batch_i, s_idx + len(s) - 1, 1] = 1 #预测第 s_idx + len - 1 个Token是不是S的终止位置

                    if s_idx == s_rand_idx: # 只有当前 SPO 的主体恰好是"训练主体"时

                        #batch_object_labels — 只标记随机选中主体的客体
                        # 条件执行 — 只标记随机选中的那个主体对应的客体和关系。这样 Model4po 要学的是：给定一个主体，找出它相关的所有客体及关系。
                        #
                        #   例子: 选中"阿莫西林"作为训练主体
                        #   SPO 列表:
                        #     阿莫西林 → 不良反应 → 皮疹        ✓ 标记 object_label (s_idx == s_rand_idx)
                        #     阿莫西林 → 适应症 → 细菌感染      ✓ 标记 object_label
                        #     高血压 → 相关症状 → 头痛          ✗ 不标记 (主体不是训练主体)

                        batch_object_labels[batch_i, o_idx, p, 0] = 1 #客体起始 + 谓词类别
                        batch_object_labels[batch_i, o_idx + len(o) - 1, p, 1] = 1 #客体结束 + 谓词类别
            batch_i += 1
            if batch_i == batch_size or i == idxs[-1]:
                yield batch_token_ids, batch_mask_ids, batch_segment_ids, batch_subject_labels, batch_subject_ids, batch_object_labels
                batch_token_ids[:, :] = 0
                batch_mask_ids[:, :] = 0
                batch_subject_ids[:, :] = 0
                batch_subject_labels[:, :, :] = 0
                batch_object_labels[:, :, :, :] = 0
                batch_i = 0

    def get_stream(self):
        return self.process_data()

    def __iter__(self):
        return self.get_stream()

# 就是
class Model4s(nn.Module):
    def __init__(self, hidden_size=768):
        super(Model4s, self).__init__()
        self.bert = BertModel.from_pretrained(config.PATH_BERT)
        for param in self.bert.parameters():
            param.requires_grad = True
        self.dropout = nn.Dropout(p=0.2)
        self.linear = nn.Linear(in_features=hidden_size, out_features=2, bias=True)
        self.sigmoid = nn.Sigmoid()

    #用 BERT 编码句子，再预测每个 token 是不是主体的起止位置
    def forward(self, input_ids, input_mask, segment_ids, hidden_size=768):
       # 第一步：BERT 编码
        hidden_states = self.bert(input_ids,
                                  attention_mask=input_mask,
                                  token_type_ids=segment_ids)[0]  # [0] 取的是 BERT 输出的第一个元素——最后一层所有 token 的隐层向量

        # 第二步：主体起止预测
        # 沿着 BERT 输出的序列做三件事：
        #
        #   hidden_states (32, 256, 768)
        #         │
        #         ▼ Dropout(0.2)    ← 随机丢弃 20% 防过拟合
        #         ▼ Linear(768→2)   ← 每个 token 输出 2 个值：[起始分, 结束分]
        #         ▼ Sigmoid          ← 压缩到 (0,1) 作为概率
        #         ▼ .pow(2)          ← 平方放大置信度差距
        #
        #   最终 output shape = (32, 256, 2)：
        #
        #   token:  [CLS]  阿  莫  西  林  治  疗  高  血  压  [SEP] [PAD]...
        #   通道0(起始):  0   0.9 0.1 0.1 0.1 0.1 0.1 0.8 0.1 0.1  0    0
        #   通道1(结束):  0   0.1 0.1 0.1 0.9 0.1 0.1 0.1 0.1 0.9  0    0
        #                  ↑____阿莫西林____↑    ↑____高血压____↑
        #
        #   - output[b, t, 0] > 阈值 → token t 是某个主体的起始位置
        #   - output[b, t, 1] > 阈值 → token t 是某个主体的结束位置
        #
        #   .pow(2) 的作用是拉大置信度差距——高概率（如 0.8→0.64）降低不多，低概率（如 0.3→0.09）大幅压低，变相起到阈值过滤的效果
        output = self.sigmoid(self.linear(self.dropout(hidden_states))).pow(2)

        return output, hidden_states


class Model4po(nn.Module):
    def __init__(self, num_p=config.num_p, hidden_size=768):
        super(Model4po, self).__init__()
        self.dropout = nn.Dropout(p=0.4)
        self.linear = nn.Linear(in_features=hidden_size, out_features=num_p * 2, bias=True)
        self.sigmoid = nn.Sigmoid()

    def forward(self, hidden_states, batch_subject_ids, input_mask):
        all_s = torch.zeros((hidden_states.shape[0], hidden_states.shape[1], hidden_states.shape[2]),
                            dtype=torch.float32)

        for b in range(hidden_states.shape[0]):
            s_start = batch_subject_ids[b][0]
            s_end = batch_subject_ids[b][1]
            s = hidden_states[b][s_start] + hidden_states[b][s_end]
            cue_len = torch.sum(input_mask[b])
            all_s[b, :cue_len, :] = s
        hidden_states += all_s

        output = self.sigmoid(self.linear(self.dropout(hidden_states))).pow(4)

        return output  # (batch_size, max_seq_len, num_p*2)

# 作用：加载谓词(关系) schema，建立双向映射。
#   具体流程：
#   1. 读 JSON 文件 — 比如 predicate.json，内容形如 {"相关疾病": {...}, "相关症状": {...}, ...}
#   2. 提取键名列表 — data.keys() 得到所有关系类型名（如"相关疾病"、"相关症状"等 23 种）
#   3. 构建双向映射：
#     - prediction2id — {"相关疾病": 0, "相关症状": 1, ...}
#     - id2predicate — {0: "相关疾病", 1: "相关症状", ...}
#   4. 存入 config — 写入全局 config 对象（config.prediction2id、config.id2predicate、config.num_p）
#   这样后续 Model4po 就知道要预测多少个谓词类别（num_p），并且训练/推理时能将模型的数字输出（如 3）反向映射回可读的中文关系名（如"症状"）。

def load_schema(path):
    with open(path, 'r', encoding='utf-8', errors='replace') as f:
        data = json.load(f) #加载predicate.json中的23 种医学关系
        predicate = list(data.keys()) #获取predicate.json中的所有key
        prediction2id = {} #定义key的和ID的正向映射 {'相关疾病': 0}
        id2predicate = {} ##定义key的和ID的反向映射 {0: '相关疾病'}
        for i in range(len(predicate)): #遍历keys集合
            prediction2id[predicate[i]] = i
            id2predicate[i] = predicate[i]
    num_p = len(predicate)
    config.prediction2id = prediction2id
    config.id2predicate = id2predicate
    config.num_p = num_p


def load_data(path): #加载'D:/CMe_KG/CMeKG/model/medical_re/train_example.json'存在text_spos数组中
    text_spos = []
    with open(path, 'r', encoding='utf-8', errors='replace') as f:
        data = json.load(f) #
        for item in data:
            text = item['text']
            spo_list = item['spo_list']
            text_spos.append({
                'text': text,
                'spo_list': spo_list
            })
    return text_spos


# 如这段代码定义了一个二元交叉熵损失函数（Binary Cross Entropy Loss）。
#
#   具体来说：
#
#   - nn.BCELoss 是 PyTorch 中的二元交叉熵损失，用于二分类任务
#   - reduction='none' 表示不对 batch 内的损失值做聚合——返回每个样本独立的损失值（而不是默认的求均值或求和）
#   - 输入 pred 是模型预测的概率（需经过 Sigmoid 激活，值域在 [0,1]），target 是真实标签（0 或 1）
#
#   常见搭配的 reduction 模式：
#
#   ┌───────────────┬────────────────────────────────────┐
#   │     模式      │                行为                │
#   ├───────────────┼────────────────────────────────────┤
#   │ 'mean' (默认) │ 返回 batch 所有样本损失的均值      │
#   ├───────────────┼────────────────────────────────────┤
#   │ 'sum'         │ 返回 batch 所有样本损失的总和      │
#   ├───────────────┼────────────────────────────────────┤
#   │ 'none'        │ 返回形状与输入相同的逐元素损失张量 │
#   └───────────────┴────────────────────────────────────┘
#
#   这里用 'none' 的原因，通常是需要在后续对损失做自定义的加权或掩码处理（例如忽略 padding 位置、对不同类别加权等），而不是简单地取平均。
#  假设 batch_size=1，句子 "高血压"（在项目中每个 token 预测是否是主体 start/end，共 2 个二分类输出）。
#
#   输入
#
#   真实标签 target（标签=1 表示是主体起始或结束位置，0 表示否）：
#
#   target = [[0, 0],  [1, 0], [0,0], [0, 1],  [0, 0]]
#             [CLS]      高      血     压     [SEP]
#
#   - token "高"(位置1) → start=1
#   - token "压"(位置3) → end=1
#
#   模型预测值 pred（Sigmoid 后的概率 [0,1]）：
#
#   pred = [[0.1, 0.2,  0.9, 0.3,  0.2, 0.8,  0.1, 0.1,  0.1, 0.1]]
#             [CLS]      高          血          压      [SEP]
#
#   计算
#
#   BCELoss(reduction='none') 对每个元素独立计算：
#
#   loss = -[target · log(pred) + (1-target) · log(1-pred)]
#
#   逐个元素：
#
#   ┌──────┬───────┬─────────────┬───────────────┬─────────────┬───────────┬─────────────┬───────────┐
#   │ 位置 │ token │ pred(start) │ target(start) │ loss(start) │ pred(end) │ target(end) │ loss(end) │
#   ├──────┼───────┼─────────────┼───────────────┼─────────────┼───────────┼─────────────┼───────────┤
#   │ 0    │ [CLS] │ 0.1         │ 0             │ 0.11        │ 0.2       │ 0           │ 0.22      │
#   ├──────┼───────┼─────────────┼───────────────┼─────────────┼───────────┼─────────────┼───────────┤
#   │ 1    │ 高    │ 0.9         │ 1             │ 0.11        │ 0.3       │ 0           │ 0.36      │
#   ├──────┼───────┼─────────────┼───────────────┼─────────────┼───────────┼─────────────┼───────────┤
#   │ 2    │ 血    │ 0.2         │ 0             │ 0.22        │ 0.8       │ 0           │ 1.61      │
#   ├──────┼───────┼─────────────┼───────────────┼─────────────┼───────────┼─────────────┼───────────┤
#   │ 3    │ 压    │ 0.1         │ 0             │ 0.11        │ 0.8       │ 1           │ 0.22      │
#   ├──────┼───────┼─────────────┼───────────────┼─────────────┼───────────┼─────────────┼───────────┤
#   │ 4    │ [SEP] │ 0.1         │ 0             │ 0.11        │ 0.1       │ 0           │ 0.11      │
#   └──────┴───────┴─────────────┴───────────────┴─────────────┴───────────┴─────────────┴───────────┘
#
#   输出形状为 [1, 5, 2]（batch=1, seq_len=5, start/end=2）：
#
#   loss = [[[0.11, 0.22],
#            [0.11, 0.36],
#            [0.22, 1.61],
#            [0.11, 0.22],
#            [0.11, 0.11]]]
#
#   关键点
#
#   - 不对损失做任何聚合——不求和、不取均值
#   - 每个位置、start/end 各自的损失都保留着独立的浮点数
#   - 这正是后续代码手动做 mean(dim=2) → mask → sum → /sum(mask) 的原因——把聚合逻辑留给调用方自己控制

def loss_fn(pred, target):
    loss_fct = nn.BCELoss(reduction='none')
    return loss_fct(pred, target)


def train(train_data_loader, model4s, model4po, optimizer):

  #  作用
  #
  # 计算每个 epoch 需要取多少个 batch，并确保至少取 1 个 batch。
  #
  # 分解
  #
  # len(train_data_loader)          → 训练样本总数（比如 100 条）
  # config.batch_size               → 32
  # len(train_data_loader) // 32    → 100 // 32 = 3（整除，向下取整）
  # max(1, 3)                       → 3
  #
  # ┌────────┬────────────┬─────────┬─────────────┬───────────────────────────────────────────────┐
  # │ 样本数 │ batch_size │ // 结果 │ max(1, ...) │                     含义                      │
  # ├────────┼────────────┼─────────┼─────────────┼───────────────────────────────────────────────┤
  # │  100   │     32     │    3    │      3      │ 每 epoch 取前 3 个 batch（96 条）             │
  # ├────────┼────────────┼─────────┼─────────────┼───────────────────────────────────────────────┤
  # │   30   │     32     │    0    │      1      │ 不足一个 batch 也取 1 个                      │
  # ├────────┼────────────┼─────────┼─────────────┼───────────────────────────────────────────────┤
  # │   0    │     32     │    0    │      1      │ 空数据也至少跑一次（防止 for 循环直接被跳过） │
  # └────────┴────────────┴─────────┴─────────────┴───────────────────────────────────────────────┘
  #
  # 为什么需要 max(1, ...)？
  #
  # 因为 train_data_loader 是 IterableDataset（生成器），len(train_data_loader) // batch_size 可能为 0：
  #
  # - 样本数 < batch_size 时，整除结果为 0
  # - 没有 max(1, 0) → num_batches = 0 → for bi in range(0): break → 整个 epoch 直接跳过，相当于没训练
  #
  # 所以 max(1, ...) 保证即使样本不够一个 batch，也至少取一个 batch 做一次更新。
  #
  # 它实际控制什么？
  #
  # 在后面的训练循环中（见 train() 第 325 行）：
  #
  # for bi, batch in enumerate(train_data_loader):
  #     if bi >= num_batches:
  #         break
  #
  # 相当于硬性截断——每个 epoch 只取前 num_batches 个 batch，后面的数据被丢弃。这是一种常见的"近似 epoch"策略：不要求精确遍历完所有数据，每个 epoch 固定的 batch 数更稳定。
  # 示例 1：正常情况（100 条数据）
  #
  # train_data = [样本1, 样本2, ..., 样本100]   # 100 条
  # loader = IterableDataset(train_data, True)
  # len(loader)     # 100
  #
  # num_batches = max(1, 100 // 32)   # max(1, 3) = 3
  #
  # 训练循环中：
  #
  # batch 0: 取样本 0~31   (样本索引 0-31)
  # batch 1: 取样本 1~32   ...等等
  # batch 2: 取样本 2~33
  # batch 3: bi >= 3? → break    ← 截断，只取了前 3 个 batch
  #
  # 每个 epoch 只处理 96 条（3×32），末尾 4 条被丢弃。因为 process_data 是生成器、数据随机打乱，下一个 epoch 丢弃的是不同样本。
  #
  # 示例 2：不足一个 batch（20 条数据）
  #
  # train_data = [样本1, ..., 样本20]    # 20 条
  # loader = IterableDataset(train_data, True)
  # len(loader)     # 20
  #
  # num_batches = max(1, 20 // 32)    # max(1, 0) = 1  ← 保证至少跑 1 次
  #
  # 训练循环中：
  #
  # batch 0: 取样本 0~19   (不足 32 条，20 条也一样 yield)
  # batch 1: bi >= 1? → break
  #
  # 没有 max(1, ...) 的话，num_batches = 0，整个 epoch 的 for 循环直接 break，一次参数更新都不做。
  #
  # 示例 3：ProcessData 内部的具体数据
  #
  # 一个 batch 实际 yield 的数组形状：
  #
  # batch_token_ids.shape       # (32, 256)   ← 32 条样本，每条 256 个 token
  # batch_mask_ids.shape        # (32, 256)   ← 注意：即便有效数据不够 32 条
  # batch_subject_labels.shape  # (32, 256, 2) ← 数组形状仍然是 (32, 256, ...)
  # batch_object_labels.shape   # (32, 256, 23, 2)
  #
  # process_data 内部预分配了固定大小 np.zeros((batch_size, max_seq_len, ...))（第 97-103 行），所以即使不满 32 条，yield 出来的数组形状不变——不足的部分保持全零，由 mask 来屏蔽。
    num_batches = max(1, len(train_data_loader) // config.batch_size) #至少保证跑一次batch
    for epoch in range(config.EPOCH):
        begin_time = time.time() #记录 epoch 开始时间，结束时计算耗时
        model4s.train() #将 Model4s 切换为训练模式（启用 Dropout、BN 等）
        model4po.train() #Model4po 也切到训练模式
        train_loss = 0. #累加器归零，用于统计该 epoch 的总损失
        for bi, batch in enumerate(train_data_loader):
            if bi >= num_batches:
                break


              # batch 的 6 个字段
              #
              # 每个字段都是在 IterableDataset.process_data() 中生成的，shape 和含义如下：
              #
              # 1. batch_token_ids — BERT 输入 token 序列（把真实元素通过Token ID表示，其他空位标0）
              #
              # - shape: (32, 256) — [batch_size, max_seq_len]
              # - 类型: np.int64 → torch.long
              # - 含义: 原始文本经过 BertTokenizer.encode() 后的 token ID 数组，已填充/截断到 256 长度
              # - 示例: [101, 1963, 2142, ..., 102, 0, 0, ...] — 首尾是 [CLS](101) 和 [SEP](102)，后面补 0
              #
              # 2. batch_mask_ids — attention mask（有真实元素的标1，其他空位标0）
              #
              # - shape: (32, 256) — [batch_size, max_seq_len]
              # - 类型: np.int64 → torch.long
              # - 含义: 哪些位置是真实 token（1），哪些是 padding（0）。[CLS] 和 [SEP] 也算真实 token
              # - 示例: [1, 1, 1, ..., 1, 0, 0, ...] — 前 len(text)+2 个为 1，后面都是 0
              # - 作用: 让 BERT 的 self-attention 忽略 padding 位置
              #
              # 3. batch_segment_ids — segment embedding （单句标0;子对：句子a标0，字句b标1;目前项目只支持单句训练）
              #
              # - shape: (32, 256) — [batch_size, max_seq_len]
              # - 类型: np.int64 → torch.long
              # - 含义: 全是 0。BERT 的 segment embedding 用于区分两个句子（NSP 任务），这里是单句任务所以全零
              #
              # 4. batch_subject_labels — 所有主体的起止位置标签
              #
              # - shape: (32, 256, 2) — [batch_size, max_seq_len, 2]
              # - 类型: np.int64 → torch.float
              # - 含义: 每个 token 的两个二分类标签：
              #   - [:, :, 0] = 1 表示该 token 是某个主体的起始位置
              #   - [:, :, 1] = 1 表示该 token 是某个主体的结束位置
              # - 标注逻辑: 遍历该句所有 SPO 三元组，只要主体和客体都在序列中存在，就标记主体位置（无条件，138-139 行）
              # - 目的: Model4s 要学会找出句中所有可能的医学主体实体
              #
              # 5. batch_subject_ids — 随机选中的"训练主体"起止索引
              #
              # - shape: (32, 2) — [batch_size, 2]
              # - 类型: np.int64 → torch.int
              # - 含义: 每一行是 [start_idx, end_idx]，指向该样本中随机选中的一个主体的位置
              # - 选择方式（第 104 行）: 从该句所有 SPO 中随机挑一个，取它的主体
              # - 目的: 这个主体作为 Model4po 的"条件"——Model4po 要根据这个给定的主体，预测它相关的所有客体和关系
              #
              # 6. batch_object_labels — 训练主体对应的客体+谓词标签
              #
              # - shape: (32, 256, 23, 2) — [batch_size, max_seq_len, num_p, 2]
              # - 类型: np.int64 → torch.float
              # - 含义:
              #   - [:, :, p, 0] = 1 表示该 token 是谓词 p 对应的客体起始位置
              #   - [:, :, p, 1] = 1 表示该 token 是谓词 p 对应的客体结束位置
              # - 标注逻辑: 只标注 training subject（随机选中的那个主体）对应的客体（第 140 行条件 s_idx == s_rand_idx）
              # - 目的: Model4po 要学会：给定一个主体，预测它和什么实体有关系（客体），以及是什么关系（谓词）
              #
              # ---
              # 整体训练循环的逻辑流
              #
              #                         ┌──────────────────────────────────────────┐
              #                         │           原始文本 + SPO 三元组            │
              #                         │   "阿莫西林用于治疗高血压引起的头痛"        │
              #                         │   [("阿莫西林","适应症","高血压"),          │
              #                         │    ("高血压","相关症状","头痛")]            │
              #                         └──────────────────────┬───────────────────┘
              #                                                │ process_data()
              #                                                ▼
              #                         ┌──────────────────────────────────────────┐
              #                         │           batch (32 条样本)               │
              #                         │  ┌─ token_ids: [101,1963,...,102,0,...]  │
              #                         │  ├─ mask_ids:  [1,1,...,1,0,0,...]       │
              #                         │  ├─ segment_ids: 全 0                    │
              #                         │  ├─ subject_labels: 标记所有主体位置      │
              #                         │  ├─ subject_ids:   随机选一个主体         │
              #                         │  └─ object_labels: 只标该主体的客体+关系  │
              #                         └──────────────────────┬───────────────────┘
              #                                                │
              #               ┌────────────────────────────────┼────────────────────────────┐
              #               │                                ▼                           │
              #               │           ┌──────────────────────────────────────┐          │
              #               │           │     Model4s: Subject Extraction      │          │
              #               │           │   BERT → Dropout → Linear(768→2)     │          │
              #               │           │         → Sigmoid → [start, end]     │          │
              #               │           │                                      │          │
              #               │  token_ids │  输出: subject_pred (32,256,2)      │          │
              #               │  mask_ids  │        + hidden_states (32,256,768)  │          │
              #               │           └──────────────────┬───────────────────┘          │
              #               │                              │                             │
              #               │                              ▼ loss4s                      │
              #               │              subject_pred vs subject_labels                │
              #               │              (模型学"找出句中所有主体")                     │
              #               │                              │                             │
              #               │                              ▼                             │
              #               │           ┌──────────────────────────────────────┐          │
              #               │           │   Model4po: Object + Relation Ext.   │          │
              #               │           │  hidden_states + subject_ids(条件)    │          │
              #               │           │  → Dropout → Linear(768→num_p×2)     │          │
              #               │ subject_ids│         → Sigmoid                   │          │
              #               │           │                                      │          │
              #               │           │  输出: object_pred (32,256,23,2)     │          │
              #               │           └──────────────────┬───────────────────┘          │
              #               │                              │                             │
              #               │                              ▼ loss4po                     │
              #               │               object_pred vs object_labels                 │
              #               │           (模型学"给定主体，预测它的所有关系+客体")         │
              #               │                              │                             │
              #               └──────────────────────────────┼─────────────────────────────┘
              #                                              ▼
              #                                 loss = loss4s + loss4po
              #                                 loss.backward()
              #                                 optimizer.step()
              #
              # 关键设计思想
              #
              # 级联抽取（Casual Extraction） — 不是一步到位预测 (s, p, o)，而是拆成两个子任务：
              #
              # ┌──────┬──────────┬───────────────────────────────────────────────────────────────────┬──────────────────────────────────────────┐
              # │ 阶段 │   模型   │                             输入→输出                             │                 学习目标                 │
              # ├──────┼──────────┼───────────────────────────────────────────────────────────────────┼──────────────────────────────────────────┤
              # │ 1    │ Model4s  │ token_ids → 每个 token 是主体起/止的概率                          │ 找出句中所有医学实体（主体候选）         │
              # ├──────┼──────────┼───────────────────────────────────────────────────────────────────┼──────────────────────────────────────────┤
              # │ 2    │ Model4po │ hidden_states + 指定主体位置 → 每个 token 在每种谓词下的起/止概率 │ 给定一个主体，找出它有哪些关系、客体是谁 │
              # └──────┴──────────┴───────────────────────────────────────────────────────────────────┴──────────────────────────────────────────┘
              #
              # 训练时的"随机主体"策略（第 104 行）：每句有多个 SPO 三元组，但每句只随机挑一个主体作为 Model4po 的"条件"。这样 Model4po 不会一次学太多，每次只聚焦一个主体。推理时则对所有检测到的主体逐一送入 Model4po，所以最终能抽完整。


            batch_token_ids, batch_mask_ids, batch_segment_ids, batch_subject_labels, batch_subject_ids, batch_object_labels = batch
            batch_token_ids = torch.tensor(batch_token_ids, dtype=torch.long)
            batch_mask_ids = torch.tensor(batch_mask_ids, dtype=torch.long)
            batch_segment_ids = torch.tensor(batch_segment_ids, dtype=torch.long)
            batch_subject_labels = torch.tensor(batch_subject_labels, dtype=torch.float)

              # 作用
              #
              # 将 4 维的客体标签 (32, 256, 23, 2) 展平为 3 维 (32, 256, 46)，使其形状匹配 Model4po 的输出。
              #
              # 形状变化
              #
              # 原始形状（process_data 中定义）:
              #   batch_object_labels: (32, 256, 23, 2)
              #   ────────────────────────────────────
              #   batch_size=32   seq_len=256   num_p=23   [起始, 结束]
              #
              # view 之后:
              #   batch_object_labels: (32, 256, 46)
              #   ────────────────────────────────
              #   batch_size=32   seq_len=256   num_p×2=46   ← 把 23×2 拍平
              #
              # 为什么需要 view？
              #
              # 因为 Model4po 的输出形状是 (32, 256, 46)，而不是 (32, 256, 23, 2)。
              #
              # 回忆 Model4po 的线性层定义：
              #
              # self.linear = nn.Linear(768, num_p * 2, bias=True)  # 23×2 = 46
              #
              # 输出形状：(32, 256, 46) — 每 2 维一组对应一个谓词的 [客体起始, 客体结束]。
              #
              # loss_fn(pred, target) 要求 pred 和 target 形状一致，所以必须把标签也 reshape 为同样的 (32, 256, 46)。
              #
              # view 的等价操作
              #
              # # view 前后数据不变，只是"视图"变了：
              #
              # # 原始 4D (32, 256, 23, 2):
              # #   [batch, seq, p, 0] = 客体起始 (谓词 p)
              # #   [batch, seq, p, 1] = 客体结束 (谓词 p)
              # #
              # #             谓词 0     谓词 1     ...  谓词 22
              # #            ┌──────┐ ┌──────┐       ┌──────┐
              # #            │起│ 结│ │起│ 结│       │起│ 结│
              # #            └──────┘ └──────┘       └──────┘
              # #
              # # view 后 3D (32, 256, 46):
              # #   [batch, seq, 0:1]   = 谓词 0 的 [起始, 结束]
              # #   [batch, seq, 2:3]   = 谓词 1 的 [起始, 结束]
              # #   ...
              # #   [batch, seq, 44:45] = 谓词 22 的 [起始, 结束]
              #
              # 完整链路
              #
              # process_data() 产出:
              #   batch_object_labels shape = (32, 256, 23, 2)
              #
              # train() 中:
              #   batch_object_labels = torch.tensor(...).view(32, 256, 46)
              #   # 形状变为 (32, 256, 46)
              #
              #   batch_object_labels_pred = model4po(hidden_states, ...)
              #   # Model4po 输出形状也是 (32, 256, 46)
              #
              #   loss4po = loss_fn(batch_object_labels_pred, batch_object_labels)
              #   # pred 和 target 形状一致 → 正确计算 BCELoss
              #
              # 如果没有 .view()，loss_fn 的输入将是 (32, 256, 46) vs (32, 256, 23, 2)，形状不匹配，PyTorch 会直接报错。

            batch_object_labels = torch.tensor(batch_object_labels, dtype=torch.float).view(config.batch_size,
                                                                                            config.max_seq_len,
                                                                                            config.num_p * 2)
            batch_subject_ids = torch.tensor(batch_subject_ids, dtype=torch.int)


              # 这段代码是 Model4s（主体抽取）的损失计算，采用掩码平均二元交叉熵损失。
              #
              # 逐步分析：
              #
              # 1. loss4s = loss_fn(...)
              # - loss_fn 是之前定义的 BCELoss(reduction='none')
              # - batch_subject_labels_pred 形状为 [batch_size, seq_len, 2]（每 token 预测是否是主体的起始/结束位置，两个二分类输出）
              # - 输出同样形状 [batch_size, seq_len, 2] 的逐元素损失
              #
              # 2. torch.mean(loss4s, dim=2, keepdim=False) * batch_mask_ids
              # - 对第 2 维（start/end 两个位置）取均值 → 形状变为 [batch_size, seq_len]
              # - 乘以 batch_mask_ids（1 表示真实 token，0 表示 padding）→ 将 padding 位置的损失置零，只保留有效 token
              #
              # 3. torch.sum(loss4s) → 求和成标量（所有有效 token 的损失之和）
              #
              # 逐步分析：
              #
              # 1. loss4s = loss_fn(...)
              # - loss_fn 是之前定义的 BCELoss(reduction='none')
              # - batch_subject_labels_pred 形状为 [batch_size, seq_len, 2]（每 token 预测是否是主体的起始/结束位置，两个二分类输出）
              # - 输出同样形状 [batch_size, seq_len, 2] 的逐元素损失
              #
              # 2. torch.mean(loss4s, dim=2, keepdim=False) * batch_mask_ids
              # - 对第 2 维（start/end 两个位置）取均值 → 形状变为 [batch_size, seq_len]
              # - 乘以 batch_mask_ids（1 表示真实 token，0 表示 padding）→ 将 padding 位置的损失置零，只保留有效 token
              #
              # 3. torch.sum(loss4s) → 求和成标量（所有有效 token 的损失之和）
              #
              # 4. loss4s / torch.sum(batch_mask_ids) → 除以有效 token 总数，得到每个有效 token 的平均损失
              #
              # 整体效果：
              # - 只对非 padding 位置计算损失
              # - 对 start/end 两个二分类输出取均值
              # - 最终得到 序列范围内每个 token 的 average BCELoss，作为模型训练的优化目标
              #
              # 与标准 BCELoss(reduction='mean') 的区别：这里手动实现了掩码平均，因为 batch 内各句长度不同，padding 位置的损失不应计入分母。
              # 场景假设
              #
              # batch_size=2，两句话长度不同，模型 max_seq_len=8：
              #
              # ┌──────┬────────────────────────────┬──────┐
              # │ 句子 │            内容            │ 长度 │
              # ├──────┼────────────────────────────┼──────┤
              # │ 句1  │ "[CLS]高 血 压 患 者[SEP]" │ 7    │
              # ├──────┼────────────────────────────┼──────┤
              # │ 句2  │ "[CLS]肺 炎[SEP]"          │ 4    │
              # └──────┴────────────────────────────┴──────┘
              #
              # padding 到统一长度 8。
              #
              # ---
              # 1. mask_ids
              #
              # 句1: [1, 1, 1, 1, 1, 1, 1, 0]     ← 7个有效, 1个padding
              # 句2: [1, 1, 1, 1, 0, 0, 0, 0]     ← 4个有效, 4个padding
              #
              # 2. batch_subject_labels（真实标签）
              #
              # 假设主体 "高血压" 在位置 1-3（token "高"=start, token "压"=end）：
              #
              # 句1: [[0,0], [1,0], [0,0], [0,1], [0,0], [0,0], [0,0], [0,0]]
              #        [CLS]    高     血     压     患     者     SEP   <pad>
              #
              # 句2 没有主体，全零：
              #
              # 句2: [[0,0], [0,0], [0,0], [0,0], [0,0], [0,0], [0,0], [0,0]]
              #        [CLS]    肺     炎     SEP   <pad>  <pad>  <pad>  <pad>
              #
              # 3. batch_subject_labels_pred（模型预测值）
              #
              # 句1: [[0.1,0.1], [0.9,0.2], [0.2,0.3], [0.1,0.8], [0.2,0.1], [0.1,0.2], [0.1,0.1], [0.0,0.0]]
              # 句2: [[0.1,0.2], [0.3,0.5], [0.1,0.9], [0.1,0.1], [0.0,0.0], [0.0,0.0], [0.0,0.0], [0.0,0.0]]
              #
              # ---
              # 逐步计算
              #
              # 第1步：BCELoss(reduction='none')
              #
              # 对逐元素计算 BCELoss：loss = -[target·log(pred) + (1-target)·log(1-pred)]
              #
              # 公式用近似值，形状 [2, 8, 2]：
              #
              # 句1 start: [0.11, 0.11, 0.22, 0.11, 0.22, 0.11, 0.11, 0.00]
              # 句1 end:   [0.11, 0.22, 0.36, 2.30, 0.11, 0.22, 0.11, 0.00]
              #                                                      ↑ SEP预测0.1,标签0 → 0.11
              #
              # 句2 start: [0.11, 0.36, 0.11, 0.11, 0.00, 0.00, 0.00, 0.00]
              # 句2 end:   [0.22, 0.69, 2.30, 0.11, 0.00, 0.00, 0.00, 0.00]
              #
              # 第2步：torch.mean(..., dim=2) — 对 start/end 取均值
              #
              # 句1: [0.11, 0.17, 0.29, 1.21, 0.17, 0.17, 0.11, 0.00]
              # 句2: [0.17, 0.53, 1.21, 0.11, 0.00, 0.00, 0.00, 0.00]
              #
              # 第3步：* batch_mask_ids — 屏蔽 padding
              #
              # 句1: [0.11, 0.17, 0.29, 1.21, 0.17, 0.17, 0.11, 0.00]  ← 最后一个置零
              # 句2: [0.17, 0.53, 1.21, 0.11, 0.00, 0.00, 0.00, 0.00]  ← 后4个置零
              #
              # 第4步：torch.sum() — 求和
              #
              # - 句1有效损失: 0.11 + 0.17 + 0.29 + 1.21 + 0.17 + 0.17 + 0.11 = 2.23
              # - 句2有效损失: 0.17 + 0.53 + 1.21 + 0.11 = 2.02
              #
              # 总和 = 2.23 + 2.02 = 4.25
              #
              # 第5步：/ torch.sum(batch_mask_ids) — 除以有效 token 数
              #
              # 有效 token 总数 = 7 (句1) + 4 (句2) = 11
              #
              # 最终损失 = 4.25 / 11 ≈ 0.386
              #
              # ---
              # 对比：如果不做掩码
              #
              # 如果用普通 BCELoss(reduction='mean')，分母是 16（所有位置）：
              #
              # 普通 mean = 4.25 / 16 ≈ 0.266     ← 被 padding 零损失稀释
              # 掩码 mean = 4.25 / 11 ≈ 0.386     ← 真正的有效损失
              #
              # 相差约 31%——padding 比例越高，偏差越大。

            batch_subject_labels_pred, hidden_states = model4s(batch_token_ids, batch_mask_ids, batch_segment_ids)
            loss4s = loss_fn(batch_subject_labels_pred, batch_subject_labels.to(torch.float32))
            loss4s = torch.mean(loss4s, dim=2, keepdim=False) * batch_mask_ids
            loss4s = torch.sum(loss4s)
            loss4s = loss4s / torch.sum(batch_mask_ids)

            batch_object_labels_pred = model4po(hidden_states, batch_subject_ids, batch_mask_ids)
            loss4po = loss_fn(batch_object_labels_pred, batch_object_labels.to(torch.float32))
            loss4po = torch.mean(loss4po, dim=2, keepdim=False) * batch_mask_ids
            loss4po = torch.sum(loss4po)
            loss4po = loss4po / torch.sum(batch_mask_ids)

            loss = loss4s + loss4po
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            train_loss += float(loss.item())
            print('batch:', bi, 'loss:', float(loss.item()))

        print('final train_loss:', train_loss / len(train_data_loader) * config.batch_size, 'cost time:',
              time.time() - begin_time)


  # 这两行代码的作用是显式释放数据加载器占用的内存。
  #
  # 逐行说明：
  #
  # 1. del train_data_loader — 删除变量引用。train_data_loader 通常在训练时持有着整个数据集的索引、缓存等数据，删除它可以解除对这块内存的引用，让 Python 知道这块内存可以被回收。
  # 2. gc.collect() — 强制触发 Python 的垃圾回收器 (Garbage Collector)，立即回收所有已无引用的对象所占用的内存。
  #
  # 通常在训练循环结束后这么做，原因有二：
  #
  # - 加速显存释放（在 GPU 上）：DataLoader 背后持有 Tensor 引用，手动 del + gc.collect() 可以更早地通知 PyTorch 释放显存，避免后续做模型评估或加载新数据时出现 OOM（显存不足）。
  # - 区分训练与推理的显存占用：训练完成后删除 DataLoader，可以让后续推理（如 evaluate() / get_triples()）拥有更大的可用显存。
  #
  # 不过，如果 train_data_loader 是局部变量，函数返回后也会自然被回收——这里的调用更多是风格化的主动清理，确保回收时机可控，不依赖作用域退出。
  #

    del train_data_loader
    gc.collect()

    return {
        "model4s_state_dict": model4s.state_dict(),
        "model4po_state_dict": model4po.state_dict(),
        "optimizer_state_dict": optimizer.state_dict(),
    }



        #  用句子 "阿莫西林适用于呼吸道感染的患者" 为例。
        #
        #   ---
        #   第 1 步：token 化
        #
        #   token_ids = tokenizer.encode("阿莫西林适用于呼吸道感染的患者", ...)
        #
        #   中文 BERT 按字切分，结果是 (max_seq_len=256)，只看有效部分：
        #
        #   ┌───────┬───────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬───────┐
        #   │ 索引  │   0   │  1  │  2  │  3  │  4  │  5  │  6  │  7  │  8  │  9  │ 10  │ 11  │ 12  │ 13  │ 14  │ 15  │  16   │
        #   ├───────┼───────┼─────┼─────┼─────┼─────┼─────┼─────┼─────┼─────┼─────┼─────┼─────┼─────┼─────┼─────┼─────┼───────┤
        #   │ token │ [CLS] │ 阿  │ 莫  │ 西  │ 林  │ 适  │ 用  │ 于  │ 呼  │ 吸  │ 道  │ 感  │ 染  │ 的  │ 患  │ 者  │ [SEP] │
        #   └───────┴───────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴───────┘
        #
        #   - len(text) = 13（中文字符数）
        #   - 第 851 行 subject_labels_pred[0, 13+2:, :] = 0 → 索引 ≥ 15 的 padding 全清零
        #   - 第 17~255 位都已 padding 到 0
        #
        #   ---
        #   第 2 步：Model4s 预测主体
        #
        #   模型输出的 subject_labels_pred 形状 (1, 256, 2)，只看前 17 个位置：
        #
        #   索引:     0    1    2    3    4    5    6    7    8    9    10   11   12   13   14   15   16
        #   token:  [CLS] 阿   莫   西   林   适   用   于   呼   吸   道   感   染   的   患   者  [SEP]
        #   ────────────────────────────────────────────────────────────────────────────────────────────────
        #   起始:   0.01 0.93 0.02 0.03 0.01 0.00 0.01 0.00 0.87 0.02 0.01 0.00 0.02 0.00 0.01 0.00 0.01
        #   结束:   0.01 0.02 0.01 0.02 0.91 0.01 0.01 0.00 0.01 0.00 0.01 0.02 0.88 0.00 0.01 0.00 0.01
        #
        #   np.where(... > 0.4)[0] 筛选后：
        #
        #   start = np.where([0.01, 0.93, 0.02, 0.03, 0.01, ...] > 0.4)[0]  # → [1, 8]
        #   end   = np.where([0.01, 0.02, 0.01, 0.02, 0.91, ...] > 0.4)[0]  # → [4, 12]
        #
        #   ---
        #   第 3 步：配对组装 subject
        #
        #   subjects = []
        #   for i in start:         # i = 1
        #       j = end[end >= i]   # end >= 1 → [4, 12]; j[0] = 4
        #       subjects.append((1, 4))
        #
        #   for i in start:         # i = 8
        #       j = end[end >= i]   # end >= 8 → [12]; j[0] = 12
        #       subjects.append((8, 12))
        #
        #   subjects = [(1, 4), (8, 12)]
        #
        #   ---
        #   第 4 步：id_str 反向映射（第 879~913 行）
        #
        #   id_str = ['[CLS]']                          # 先把 [CLS] 放进去
        #   # 逐 token decode，循环直到碰到 [SEP] (102)
        #   # id_str = ['[CLS]', '阿', '莫', '西', '林', '适', '用', '于', '呼', '吸', '道', '感', '染', '的', '患', '者']
        #
        #   ---
        #   第 5 步：Model4po 预测客体 + 谓词
        #
        #   对 subject (1, 4)（"阿莫西林"）做客体预测：
        #
        #   索引:     0    1    2    3    4    5    6    7    8    9    10   11   12   13   14   15   16
        #   ────────────────────────────────────────────────────────────────────────────────────────────────
        #   客体起始:  ...  ...  ...  ...  ...  ...  ...  ... 0.88 0.02 0.01 0.03 0.01 0.00  ...
        #   客体结束:  ...  ...  ...  ...  ...  ...  ...  ... 0.01 0.02 0.00 0.04 0.86 0.00  ...
        #   谓词 ID:  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  15   15   15   15   ...
        #
        #   start > 0.4: [8], end > 0.4: [12], 谓词 = 15
        #
        #   spoes.append(((1, 4), 15, (8, 12)))
        #
        #   对 subject (8, 12)（"呼吸道感染"）做客体预测——假设没命中，跳过。
        #
        #   ---
        #   第 6 步：从索引还原文本（第 914~922 行）
        #
        #   for s, p, o in spoes:
        #       # s = (1, 4), p = 15, o = (8, 12)
        #       sub = ''.join(id_str[1:4+1])    # id_str[1:5] = "阿莫西林"
        #       obj = ''.join(id_str[8:12+1])   # id_str[8:13] = "呼吸道感染"
        #       pred = id2predicate[15]         # "适应症"
        #
        #   最终输出：
        #
        #   res = [("阿莫西林", "适应症", "呼吸道感染")]
        #
        #   ---
        #   整理
        #
        #   代码执行流水线：
        #
        #   token 化      → 模型预测 → 阈值过滤      → 配对标定          → 文本还原
        #                      ↓
        #               subject_labels_pred
        #               shape (1, 256, 2)
        #                   ↓
        #            start = [1, 8]             start = [1, 8]
        #            end   = [4, 12]   ──────→  end   = [4, 12]
        #            (通道 0 > 0.4)               ↓ 配对
        #            (通道 1 > 0.4)
        #                                  subjects = [(1, 4), (8, 12)]
        #                                                ↓ Model4po
        #                                  spoes = [((1, 4), 15, (8, 12))]
        #                                                ↓
        #                                  id_str[1:5]   = "阿莫西林"
        #                                  id_str[8:13]  = "呼吸道感染"
        #                                  id2predicate[15] = "适应症"
        #                                                ↓
        #                                  ("阿莫西林", "适应症", "呼吸道感染")


def extract_spoes(text, model4s, model4po):
    """
    return: a list of many tuple of (s, p, o)
    """
    # 处理text
    #代码解析：推理时关掉 autograd，省显存、省计算，并且不影响结果
    with torch.no_grad():
        tokenizer = config.tokenizer
        max_seq_len = config.max_seq_len
        token_ids = torch.tensor(
            tokenizer.encode(text, max_length=max_seq_len, padding='max_length', truncation=True,
                             add_special_tokens=True)).view(1, -1)
        if len(text) > max_seq_len - 2:
            text = text[:max_seq_len - 2]
        mask_ids = torch.tensor([1] * (len(text) + 2) + [0] * (max_seq_len - len(text) - 2)).view(1, -1)
        segment_ids = torch.tensor([0] * max_seq_len).view(1, -1)
        subject_labels_pred, hidden_states = model4s(token_ids, mask_ids, segment_ids)
        subject_labels_pred = subject_labels_pred.cpu()
        subject_labels_pred[0, len(text) + 2:, :] = 0 #用 mask 把 padding 区域的预测"关掉"，模型只能从有效 token 区间内预测实体

          # 先说结论：这两行代码把模型预测的连续概率值转成离散的实体位置索引。
          #
          # 逐步拆解：
          #
          # 1. subject_labels_pred 的形状
          #
          # (1, max_seq_len=256, 2)
          #  ↑         ↑            └─ 通道 0: 当前 token 是"主体起始"的概率
          #  batch     │               通道 1: 当前 token 是"主体结束"的概率
          #          所有 token 位置（含 padding）
          #
          # 2. subject_labels_pred[0, :, 0]
          #
          # 取第 0 个样本的"起始概率"一维数组，长度 256，每个值在 0~1 之间。
          #
          # 3. > 0.4
          #
          # 阈值过滤 — 概率超过 0.4 才算数。比如输出可能是：
          #
          # 位置:  0   1   2   3   4   5   6   7  ...  ← [CLS] 阿 莫 西  林  治  疗  高  ...
          # 起始:  0.01  0.95  0.03  0.10  0.89  0.02  0.01  ...
          # 结束:  0.01  0.02  0.88  0.04  0.10  0.91  0.01  ...
          #
          # > 0.4 后起始为 [1, 4]，结束为 [2, 5]。
          #
          # 4. np.where(...)[0]
          #
          # np.where 返回一个元组 (array_of_indices,)，[0] 把它展开成一维数组。
          #
          # 最终配对
          #
          # for i in start:       # 每个起始位置
          #     j = end[end >= i] # 找它后面的第一个结束位置
          #     ...
          #
          # 配好后得到 [(1,2), (4,5)]，即 "阿莫西林"在第 1~2 token，"高血压"在第 4~5 token。
          #
          # 模型输出的是"每个 token 分类概率"，这两行代码就是 从概率还原为具体实体边界，0.4 是训练时调出来的经验阈值，调低则召回更多但可能误判，调高则更精确但可能漏掉
          # 以输入句子 "阿莫西林治疗高血压" 为例（6个字 + [CLS] + [SEP] = 8 有效 token）：
          #
          # 1. 模型输出的起始/结束概率（简化示意）
          #
          # token:   [CLS]   阿     莫     西     林     治疗    高     血压  [SEP]  [PAD] ...
          # 索引:      0      1      2      3      4      5      6      7      8      9
          # ─────────────────────────────────────────────────────────────────────────────
          # 起始:    0.01   0.95   0.03   0.02   0.10   0.02   0.89   0.01   0.01   0.00  ...
          # 结束:    0.01   0.02   0.04   0.003   0.88   0.91   0.01   0.02   0.01   0.00  ...
          #
          # 2. np.where(subject_labels_pred[0, :, 0] > 0.4)[0] → 起始位置
          #
          # 只看起始通道，逐个扫描 > 0.4 的：
          #
          # ┌──────┬──────┬───────────┐
          # │ 索引 │ 概率 │  > 0.4?   │
          # ├──────┼──────┼───────────┤
          # │ 1    │ 0.95 │ ✅  → 候选 │
          # ├──────┼──────┼───────────┤
          # │ 6    │ 0.89 │ ✅  → 候选 │
          # └──────┴──────┴───────────┘
          #
          # start = [1, 6]
          #
          # 3. np.where(subject_labels_pred[0, :, 1] > 0.4)[0] → 结束位置
          #
          # 看结束通道：
          #
          # ┌──────┬──────┬───────────┐
          # │ 索引 │ 概率 │  > 0.4?   │
          # ├──────┼──────┼───────────┤
          # │ 4    │ 0.88 │ ✅  → 候选 │
          # ├──────┼──────┼───────────┤
          # │ 5    │ 0.91 │ ✅  → 候选 │
          # └──────┴──────┴───────────┘
          #
          # end = [4, 5]
          #
          # 4. 配对（组装实体）
          #
          # for i in start:        # i = 1 → 模型说"位置 1 可能是一个实体的开头"
          #     j = end[end >= i]  # 找结束数组中 ≥1 的: [4, 5] → 第一个是 4
          #     subjects.append((1, 4))  # 得到实体 span (1, 4)
          #
          # for i in start:        # i = 6 → "位置 6 可能也是一个实体的开头"
          #     j = end[end >= i]  # 找结束数组中 ≥6 的: [] → 没有，这个起始被丢弃
          #
          # 最终 subjects = [(1, 4)]，反向映射到原文 token 索引 1~4 → "阿莫西林"。
          #
          # 可视化流程
          #
          # 位置:  [CLS]  阿    莫    西    林    治疗   高    血压  [SEP]
          # 起始:  0.01  0.95  0.03  0.02  0.10  0.02  0.89  0.01  0.01
          #                ↑                           ↑
          #               > 0.4                      > 0.4
          #                │                           │
          # 结束:  0.01  0.02  0.04  0.003  0.88  0.91  0.01  0.02  0.01
          #                                 ↑      ↑
          #                               > 0.4   > 0.4
          #                                 │      │
          #                ┌────────────────┘      └─────────┐
          #                ↓                                 ↓
          #            (1,4) → "阿莫西林"                 (6,5) 无效，丢弃
          #
          # 总结：这两行代码就是"捡起模型说哪里是开头、哪里是结尾，然后配对组装成实体"，中间用的 0.4 就是个过滤噪声的门槛。

        start = np.where(subject_labels_pred[0, :, 0] > 0.4)[0]
        end = np.where(subject_labels_pred[0, :, 1] > 0.4)[0]

        subjects = []
        for i in start:
            j = end[end >= i]
            if len(j) > 0:
                j = j[0]
                subjects.append((i, j))

        if len(subjects) == 0:
            return []

          #   这行代码把 subjects 列表转换成 PyTorch 张量，然后拍平保留 batch 维度。一步步拆：
          #
          # 1. subjects 的内容
          #
          # subjects = [(1, 4), (8, 12)]   # 两个主体，每个是 (start, end)
          #
          # 2. torch.tensor(subjects)
          #
          # # Python list of tuples → PyTorch 张量
          # tensor([[1, 4],
          #         [8, 12]])    # shape (2, 2)
          #
          # 3. .view(1, -1)
          #
          # - 1 → batch 维度为 1
          # - -1 → 剩余维度自动计算（原有 4 个元素，所以是 4）
          #
          # tensor([[1, 4, 8, 12]])    # shape (1, 4)
          #
          # 把 (2, 2) 拉直成 (1, 4)。
          #
          # ---
          # 为什么这样处理？ 看它怎么被用的：
          #
          # # extract_spoes 第 972 行
          # for s in subjects:
          #     object_labels_pred = model4po(hidden_states, subject_ids, mask_ids)
          #
          # 而在 Model4po.forward()（第 239-241 行）中：
          #
          # for b in range(hidden_states.shape[0]):        # hidden_states batch=1
          #     s_start = batch_subject_ids[b][0]           # 取 subject_ids[0][0] → start
          #     s_end = batch_subject_ids[b][1]             # 取 subject_ids[0][1] → end
          #     s = hidden_states[b][s_start] + hidden_states[b][s_end]  # 取该 span 的起止向量并求和
          #
          # 所以 view(1, -1) 后的形状 (1, 4) 意味着：
          # - batch_subject_ids[0] = [1, 4, 8, 12]
          # - batch_subject_ids[0][0] = 1, batch_subject_ids[0][1] = 4
          #
          # 实际上只用了每个 subject 的起始/结束 index，但 .view(1,-1) 把所有 subject 的坐标"首尾相接"进了同一个 batch。同一句里多个 subject 时，因为这个循环只迭代 batch_size=1，所以只用到了第一个 subject 的坐标。
          #
          # 本质是为了匹配 Model4po 的 batch 接口：它期望输入形状 (batch, ...)，而一个句子的所有 subject 位置拼接成一行。
        spoes = []
          # 改前：循环外拼装所有主体，Model4po 只用第一组
          # subject_ids = torch.tensor(subjects).view(1, -1)
          # for s in subjects:
          #     object_labels_pred = model4po(hidden_states, subject_ids, mask_ids)
          #
          # # 改后：每轮循环只用当前主体的坐标
          # for s in subjects:
          #     subject_ids = torch.tensor(s).view(1, -1)
          #     object_labels_pred = model4po(hidden_states, subject_ids, mask_ids)

        for s in subjects:
            subject_ids = torch.tensor(s).view(1, -1)  # 只用当前主体坐标，而非拼接所有主体
            object_labels_pred = model4po(hidden_states, subject_ids, mask_ids)
            object_labels_pred = object_labels_pred.view((1, max_seq_len, config.num_p, 2)).cpu()
            object_labels_pred[0, len(text) + 2:, :, :] = 0
            start = np.where(object_labels_pred[0, :, :, 0] > 0.4)
            end = np.where(object_labels_pred[0, :, :, 1] > 0.4)

            for _start, predicate1 in zip(*start):
                for _end, predicate2 in zip(*end):
                    if _start <= _end and predicate1 == predicate2:
                        spoes.append((s, predicate1, (_start, _end)))
                        break

    id_str = ['[CLS]']
    i = 1
    index = 0
    while i < token_ids.shape[1]:
        if token_ids[0][i] == 102:
            break

        word = tokenizer.decode(token_ids[0, i:i + 1])
        word = re.sub('#+', '', word)
        if word != '[UNK]':
            id_str.append(word)
            index += len(word)
            i += 1
        else:
            j = i + 1
            while j < token_ids.shape[1]:
                if token_ids[0][j] == 102:
                    break
                word_j = tokenizer.decode(token_ids[0, j:j + 1])
                if word_j != '[UNK]':
                    break
                j += 1
            if token_ids[0][j] == 102 or j == token_ids.shape[1]:
                while i < j - 1:
                    id_str.append('')
                    i += 1
                id_str.append(text[index:])
                i += 1
                break
            else:
                index_end = text[index:].find(word_j)
                word = text[index:index + index_end]
                id_str.append(word)
                index += index_end
                i += 1
    res = []
    for s, p, o in spoes:
        s_start = s[0]
        s_end = s[1]
        sub = ''.join(id_str[s_start:s_end + 1])
        o_start = o[0]
        o_end = o[1]
        obj = ''.join(id_str[o_start:o_end + 1])
        res.append((sub, config.id2predicate[p], obj))

    return res


class SPO(tuple):
    def __init__(self, spo):
        self.spox = (
            tuple(config.tokenizer.tokenize(spo[0])),
            spo[1],
            tuple(config.tokenizer.tokenize(spo[2])),
        )

    def __hash__(self):
        return self.spox.__hash__()

    def __eq__(self, spo):
        return self.spox == spo.spox


def evaluate(data, is_print, model4s, model4po):
    X, Y, Z = 1e-10, 1e-10, 1e-10
    for d in data:
        R = set([SPO(spo) for spo in extract_spoes(d['text'], model4s, model4po)])  # 模型提取出的三元组数目
        T = set([SPO(spo) for spo in d['spo_list']])  # 正确的三元组数目
        if is_print:
            print('text:', d['text'])
            print('R:', R)
            print('T:', T)
        X += len(R & T)  # 模型提取出的三元组数目中正确的个数
        Y += len(R)  # 模型提取出的三元组个数
        Z += len(T)  # 正确的三元组总数
    f1, precision, recall = 2 * X / (Y + Z), X / Y, X / Z

    return f1, precision, recall



# ● run_train() 的完整流程：
#
#   1. 加载 schema — 调用 load_schema(config.PATH_SCHEMA)，读取关系谓词列表，建立 id ↔ 关系名的双向映射
#   2. 加载数据 — 读取 JSON 格式的训练数据，随机打乱
#   3. 8:2 划分 — 前 80% 作为训练集，后 20% 作为验证集（注意：验证集在这里只划分了，没在函数内使用，train() 内部应该会处理）
#   4. 加载 checkpoint — torch.load(config.PATH_MODEL) 加载预训练好的模型权重（这就是报错的那行）
#   5. 初始化模型 — 创建 Model4s（主体抽取）和 Model4po（客体+谓词抽取），从 checkpoint 恢复权重
#   6. 配置优化器 — 把两个模型的参数合并，用 AdamW 优化器，对 bias 和 LayerNorm 参数不做权重衰减（weight_decay=0.0），其余参数 weight_decay=0.01；并从 checkpoint 恢复优化器状态
#   7. 开始训练 — 调用 train() 函数，返回新的 checkpoint
#
#   本质：这是微调 (fine-tune) 流程，在已有预训练模型基础上继续训练，而不是从零开始训练。

def run_train():
    load_schema(config.PATH_SCHEMA)
    train_path = config.PATH_TRAIN
    all_data = load_data(train_path) #加载train_example.json数据
    random.shuffle(all_data) #用途是：打乱数据集样本顺序，避免数据按固定顺序训练导致模型偏向、训练效果差

    # 8:2划分训练集、验证集
    # 1. 计算分割下标：总样本数 × 0.8，转整数
    idx = int(len(all_data) * 0.8)
    # 2. 切片取前80%作为训练集（下标 0 ~ idx-1）
    train_data = all_data[:idx]
    # 3. 切片取后20%作为验证集（下标 idx ~ 末尾）
    valid_data = all_data[idx:]

    # train
    train_data_loader = IterableDataset(train_data, True)
    num_train_data = len(train_data)
    #1.torch.load(config.PATH_MODEL) — 从磁盘加载之前训练好的checkpoint文件（model_re.pkl）
    #2.map_location = torch.device('cpu') — 强制将所有张量加载到CPU上，而不是试图加载到保存时的设备（CUDA）
    checkpoint = torch.load(config.PATH_MODEL, map_location=torch.device('cpu'))

   #1. 初始化模型 + 加载预训练权重
    model4s = Model4s()
    model4s.load_state_dict(checkpoint['model4s_state_dict']) #创建主体抽取模型，从 checkpoint 恢复之前训练好的权重。
    #需要GPU环境
    # model4s.cuda()

    model4po = Model4po()
    model4po.load_state_dict(checkpoint['model4po_state_dict']) #创建客体+谓词抽取模型，同样恢复权重。
    # model4po.cuda()

    # 2. 合并两个模型的参数
    param_optimizer = list(model4s.named_parameters()) + list(model4po.named_parameters()) #把 Model4s 和 Model4po 的所有参数合并到一个列表（含 BERT 的 1.1 亿参数 + 两个线性层），供优化器统一更新

   #3. 分组设置权重衰减
    no_decay = ['bias', 'LayerNorm.bias', 'LayerNorm.weight']
    optimizer_grouped_parameters = [
        {'params': [p for n, p in param_optimizer if not any(nd in n for nd in no_decay)], 'weight_decay': 0.01},  #不是 bias/LayerNorm,BERT 的权重矩阵、Linear 层的权重
        {'params': [p for n, p in param_optimizer if any(nd in n for nd in no_decay)], 'weight_decay': 0.0} #是 bias/LayerNorm,偏置项、LayerNorm 参数
    ]

    #4. 创建优化器 + 恢复状态
    #使用 AdamW 优化器，学习率 1e-5（BERT 微调典型值），并从 checkpoint 恢复优化器的动量/梯度历史状态，确保继续训练时学习率调度连续
    lr = config.learning_rate
    optimizer = AdamW(optimizer_grouped_parameters, lr=lr)
    optimizer.load_state_dict(checkpoint['optimizer_state_dict'])

     #5. 训练入口
    checkpoint = train(train_data_loader, model4s, model4po, optimizer)

    del train_data
    gc.collect()
    # save
    model_path = config.PATH_SAVE
    torch.save(checkpoint, model_path)
    print('saved!')

    # valid
    model4s.eval()
    model4po.eval()
    f1, precision, recall = evaluate(valid_data, True, model4s, model4po)
    print('f1: %.5f, precision: %.5f, recall: %.5f' % (f1, precision, recall))


def load_model():
    load_schema(config.PATH_SCHEMA)
    checkpoint = torch.load(config.PATH_MODEL, map_location='cpu')

    model4s = Model4s()
    model4s.load_state_dict(checkpoint['model4s_state_dict'])
    # model4s.cuda()

    model4po = Model4po()
    model4po.load_state_dict(checkpoint['model4po_state_dict'])
    # model4po.cuda()

    return model4s, model4po


    # get_triples 是推理入口，负责把长文本切段后逐句抽取三元组，最终输出结构化结果。
    #
    #   核心逻辑
    #
    #   输入: "据报道称，新冠肺炎患者经常会发热、咳嗽，少部分患者会胸闷、乏力，其病因包括：自身免疫系统缺陷。"
    #
    #   分句: ["据报道称", "新冠肺炎患者经常会发热、咳嗽", "少部分患者会胸闷、乏力", ...]
    #           ↓ 每句限长 128 字
    #   逐句抽: extract_spoes(每句) → [(主体, 谓词, 客体), ...]
    #           ↓ 合并
    #   输出: [{"text": "新冠肺炎患者经常会发热、咳嗽", "triples": [("新冠肺炎", "临床表现", "发热"), ...]}, ...]

      # 方法设计目的
      #
      # 存在 get_triples 是因为BERT 有输入长度限制（max_seq_len=256），而一篇药品说明书可能几百到几千字。所以它：
      #
      # ┌─────────────────┬──────────────────┬──────────────────────────────────────────┐
      # │      步骤       │       作用       │                为什么需要                │
      # ├─────────────────┼──────────────────┼──────────────────────────────────────────┤
      # │ split('。')     │ 按句号切分成短句 │ 保持语义完整，每句一个完整陈述           │
      # ├─────────────────┼──────────────────┼──────────────────────────────────────────┤
      # │ [:128]          │ 超长句截断       │ 加上 [CLS]/[SEP] 后不超 BERT 上限（256） │
      # ├─────────────────┼──────────────────┼──────────────────────────────────────────┤
      # │ extract_spoes() │ 逐句抽取         │ 核心 NLP 推断，模型单次处理一个短句      │
      # ├─────────────────┼──────────────────┼──────────────────────────────────────────┤
      # │ 合并结果        │ 返回结构化数组   │ 保留每句原文，方便溯源和拼接             │
      # └─────────────────┴──────────────────┴──────────────────────────────────────────┘
      #
      # 和训练的关系
      #
      # 训练时不经过 get_triples。训练用的是 train() 循环，直接调 process_data() 生成 batch → Model4s + Model4po。get_triples 只在推理阶段使用，比如 demo.py 里那样：加载训练好的模型 → 调用 get_triples(新文本) 得到结果。

def get_triples(content, model4s, model4po):
    if len(content) == 0:
        return []
  #  改前：
  # text_list = content.split('。')[:-1] # 按句号分句
  #
  # 改后：
  # text_list = [t for t in content.split('。') if t] # 按句号分句，过滤空串
  #
  # 为什么改： 原来的 [:-1] 是为了去掉句号结尾产生的空串（比如"a。b。" split 后是 ["a", "b", ""]，去掉最后一个）。但文本没有句号时（比如 "高血压病人不可食用阿莫西林等药物"），split 结果是 ["高血压病人不可食用阿莫西林等药物"]，[:-1] 直接把它删光了，所以 RE 返回空。
  #
  # 改后的 [t for t in ... if t] 只过滤空串，保留所有有内容的分句，不管有没有句号。

    text_list = [t for t in content.split('。') if t] # 按句号分句，过滤空串
    res = []
    for text in text_list:
        if len(text) > 128:
            text = text[:128]  # 每句限长 128 字
        triples = extract_spoes(text, model4s, model4po) # 逐句抽取
        res.append({
            'text': text,
            'triples': triples
        })
    return res

if __name__ == "__main__":

    with open(config.PATH_TRAIN, 'r', encoding="utf-8", errors='replace') as f:
        data = json.load(f)

        f1=open("train.json","w")

        json.dump(data,f1,ensure_ascii=False,indent=True)
        print("finish")

    # load_schema(config.PATH_SCHEMA)
    # model4s, model4po = load_model()
    #
    # text = "据报道称，新冠肺炎患者经常会发热、咳嗽，少部分患者会胸闷、=乏力，其病因包括: 1.自身免疫系统缺陷\n2.人传人。"
    #
    # res = get_triples(text, model4s, model4po)

    # print(res)

